#################################################
# Global Settings
#################################################
server.port = 8080
spring.jmx.enabled = false
endpoints.enabled = true
endpoints.health.enabled = true
endpoints.shutdown.sensitive = false
endpoints.shutdown.enabled = false
management.security.enabled = false

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(:){faint} %m%n%wEx

#################################################
# JorManager Settings
#################################################

# admin password hash for JorManager
# To generate, run
# $ ./jormanager.jar passwd
# To test your password, run
# $ ./jormanager.jar passwdtest '$argon2id$v=19$m=4096,t=3,p=1$ce4OFwws/HLvGe9d6SrirQ$Mm6ylvTOqGB8v+rzldru2zcvWnT/OdCB51i/GgRe6uP'
jormanager.admin.password = $argon2id$v=19$m=4096,t=3,p=1$ce4OFwws/HLvGe9d6SrirQ$Mm6ylvTOqGB8v+rzldru2zcvWnT/OdCB51i/GgRe6uP
#
# number of jormungandr nodes to spin up
jormanager.nodecount = 10
#
# To make a node passive (never assigned leadership and never firewall protected), set it to true
jormanager.node.passive = false, false, false, false, false, false, false, false, false, false
#
# number of milliseconds to stagger node startup (default 10 seconds)
jormanager.node_stagger_ms = 10000
#
# milliseconds between each new leader election cycle
jormanager.leader_election_delay_ms = 20000
#
# max blocks behind the leader a node can be and not be killed
jormanager.max_blocks_behind = 5
#
# uptime in seconds to allow a node to be behind leader before we start checking (default 3 mins)
jormanager.node_probation_secs = 180
#
# time in milliseconds to let a node flounder during bootstrapping before we kill it and try again (default 5 mins)
jormanager.max_bootstrap_ms = 300000
#
# settings for pooltool
jormanager.pooltool.enabled = true
jormanager.pooltool.jormver.enabled = true
jormanager.pooltool.poolId = deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
jormanager.pooltool.userId = deadbeef-dead-dead-dead-deadbeefdead
jormanager.pooltool.genesisPref = 8e4d2a343f3dcf93
#
# location for the historical block log. This keeps track of blocks you've minted. If it doesn't exist yet, create it
# and put an empty array inside it `echo "[]" > /var/www/html/blocks.json`
jormanager.block_log = /var/www/html/blocks.json
#
# location for the current cluster stats. This can be used to drive dashboards
jormanager.stats_log = /var/www/html/jormanager-stats.json
#
# Enable/disable management of ufw firewall. By enabling/disabling firewall access to our jormungandr instance,
# we take load off of jormungandr having to reject so many incoming connections when we're close to our max connections.
# note: the user that jormanager runs under must have no-pasword sudo access to the ufw command.
# $ sudo visudo
# ** add the line something like... **
# westbam ALL=NOPASSWD: /usr/sbin/ufw
jormanager.ufw.enabled = false
jormanager.ufw.allow = /usr/bin/sudo /usr/sbin/ufw allow 33{pid}/tcp
jormanager.ufw.deny = /usr/bin/sudo /usr/sbin/ufw reject 33{pid}/tcp
#
# Open up firewall if node connections drops below this number
jormanager.ufw.lower_limit = 100
#
# Close off firewall if node connections climbs above this number
jormanager.ufw.upper_limit = 120
#
# Use ss command to estimate connected peers instead of jcli network stats get rest call
jormanager.lightweight.peercount=true


#################################################
# Jormungandr Settings
#################################################
#
# Path to the jormungandr executable. You can omit pid, but I like to have multiple copies of the exe so you can see
# them in `top`. pid is zero-padded to 2 chars
jormanager.jormungandr.process = /home/westbam/.cargo/bin/jormungandr{pid}
#
# Path to the jormungandr storage folder.
jormanager.jormungandr.storage = /home/westbam/cardano/storage{pid}
#
# node config file location. pid is zero-padded to 2 chars
jormanager.jormungandr.config = /home/westbam/cardano/itn_rewards_v1-config{pid}.yaml
#
# genesis hash to use when starting jormungandr
jormanager.jormungandr.genesis = 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
#
# path to the secret file for this stakepool
jormanager.jormungandr.secret = /home/westbam/cardano/bluecheesestakehouse_poolsecret.yaml
#
# path to the secret file for this stakepool in json format. We need to use the json format when promoting a node to leader
jormanager.jormungandr.secret_json = /home/westbam/cardano/bluecheesestakehouse_poolsecret.json
#
# Rest Api URL pattern for jormungandr. Process 4 would be: http://127.0.0.1:3404/api/, Process 27 would be http://127.0.0.1:3427/api/
# pid is zero-padded to 2 chars
jormanager.jormungandr.rest_api_url = http://127.0.0.1:34{pid}/api/
#
# Jormungandr log file location. pid is zero-padded to 2 chars
jormanager.jormungandr.log_location = /home/westbam/cardano/jormungandr{pid}.log

