# ---- Globals ----
server.address=127.0.0.1
server.port=8787

# ---- Database Information ----
spring.datasource.url=jdbc:h2:file:./jormanager
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.liquibase.change-log=classpath:db/liquibase-changelog.xml
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true

# ---- Quiet some logs ----
logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.net.schmizz.sshj=WARN
logging.level.com.hierynomus.sshj=WARN
# ---- PoolTool ----
pooltool.apikey=

# ---- libsodium ----
libsodium.path="/usr/local/lib/libsodium.so"