# ---- Globals ----
server.address=127.0.0.1
server.port=8787
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=1m

# ---- Database Information ----
spring.datasource.url=jdbc:postgresql://localhost:5432/jormanager
spring.datasource.username=jormanager
spring.datasource.password=jormanager

spring.liquibase.change-log=classpath:db/liquibase-changelog.xml
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.current_session_context_class=thread
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- Quiet some logs ----
logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.net.schmizz.sshj=WARN
logging.level.com.hierynomus.sshj=WARN
# ---- PoolTool ----
pooltool.apikey=
# ---- libsodium ----
libsodium.path=/usr/local/lib/libsodium.so